#!/usr/bin/env zsh

here=$0:A:h
list=$here/filelist.txt

zmodload zsh/mapfile
files=( ${(f)mapfile[filelist.txt]} )
for file in $files; do
    cat >$file <<EOF
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="refresh" content="0; url='https://archive.zhimingwang.org/blog/${file}'">
  <title>dl? cmplnts?</title>
</head>
<body>
  <p>This page has been moved to <a href="https://archive.zhimingwang.org/blog/${file}">archive.zhimingwang.org</a>.</p>
  <script>setInterval(function () { window.location.hostname = 'archive.zhimingwang.org' }, 1000)</script>
</body>
</html>
EOF
done
